openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /api/budgets/:
    get:
      operationId: api_budgets_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BudgetList'
          description: ''
    post:
      operationId: api_budgets_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BudgetList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BudgetList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BudgetList'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BudgetList'
          description: ''
    put:
      operationId: api_budgets_update
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Budget'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Budget'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Budget'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Budget'
          description: ''
    patch:
      operationId: api_budgets_partial_update
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBudget'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBudget'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBudget'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Budget'
          description: ''
    delete:
      operationId: api_budgets_destroy
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/budgets/{budget_id}/expenses/:
    get:
      operationId: api_budgets_expenses_list
      parameters:
      - in: path
        name: budget_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExpenseList'
          description: ''
    post:
      operationId: api_budgets_expenses_create
      parameters:
      - in: path
        name: budget_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ExpenseList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ExpenseList'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseList'
          description: ''
  /api/budgets/{budget_id}/expenses/{expense_id}:
    get:
      operationId: api_budgets_expenses_retrieve
      parameters:
      - in: path
        name: budget_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: expense_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
          description: ''
    put:
      operationId: api_budgets_expenses_update
      parameters:
      - in: path
        name: budget_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: expense_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Expense'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Expense'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Expense'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
          description: ''
    patch:
      operationId: api_budgets_expenses_partial_update
      parameters:
      - in: path
        name: budget_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: expense_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedExpense'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedExpense'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedExpense'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
          description: ''
    delete:
      operationId: api_budgets_expenses_destroy
      parameters:
      - in: path
        name: budget_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: expense_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/categories/:
    get:
      operationId: api_categories_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Categories'
          description: ''
    post:
      operationId: api_categories_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categories'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Categories'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Categories'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
          description: ''
components:
  schemas:
    Budget:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 120
        budget_limit:
          type: string
          format: decimal
          pattern: ^-?\d{0,6}(?:\.\d{0,2})?$
        description:
          type: string
          nullable: true
          maxLength: 200
        created_timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - budget_limit
      - created_timestamp
      - id
      - name
    BudgetList:
      type: object
      properties:
        name:
          type: string
          maxLength: 120
        description:
          type: string
          nullable: true
          maxLength: 200
        created_timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_timestamp
      - name
    Categories:
      type: object
      properties:
        name:
          type: string
          maxLength: 120
        description:
          type: string
          nullable: true
          maxLength: 250
      required:
      - name
    Expense:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 120
        total:
          type: string
          format: decimal
          pattern: ^-?\d{0,6}(?:\.\d{0,2})?$
        description:
          type: string
          nullable: true
          maxLength: 200
        budget_id:
          type: string
          format: uuid
        category:
          type: string
          format: uuid
          nullable: true
        created_timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - budget_id
      - created_timestamp
      - id
      - name
      - total
    ExpenseList:
      type: object
      properties:
        name:
          type: string
          maxLength: 120
        expense_items:
          type: array
          items:
            $ref: '#/components/schemas/Expense'
          readOnly: true
      required:
      - expense_items
      - name
    PatchedBudget:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 120
        budget_limit:
          type: string
          format: decimal
          pattern: ^-?\d{0,6}(?:\.\d{0,2})?$
        description:
          type: string
          nullable: true
          maxLength: 200
        created_timestamp:
          type: string
          format: date-time
          readOnly: true
    PatchedExpense:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 120
        total:
          type: string
          format: decimal
          pattern: ^-?\d{0,6}(?:\.\d{0,2})?$
        description:
          type: string
          nullable: true
          maxLength: 200
        budget_id:
          type: string
          format: uuid
        category:
          type: string
          format: uuid
          nullable: true
        created_timestamp:
          type: string
          format: date-time
          readOnly: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
