# Generated by Django 4.1.7 on 2023-03-23 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('monthly_limit', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('created_timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('r', 'read'), ('w', 'write'), ('a', 'admin')], default='read', max_length=2)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickbudget.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('total', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('created', models.TimeField(null=True, verbose_name=datetime.date.today)),
                ('created_timestamp', models.TimeField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickbudget.budget')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickbudget.category')),
            ],
        ),
    ]
