# Generated by Django 4.1.7 on 2023-04-28 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quickbudget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
