# Generated by Django 4.1.7 on 2023-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickbudget", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    (1, "Groceries"),
                    (2, "Bills"),
                    (3, "Entertainment"),
                    (4, "Pleasure"),
                    (5, "Taxes"),
                    (6, "Health"),
                    (7, "Transportation"),
                    (8, "Loans / payments"),
                ],
                default=None,
                max_length=120,
            ),
        ),
    ]
