# Generated by Django 4.1.7 on 2023-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickbudget", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
