# Generated by Django 4.1.7 on 2023-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbudget', '0002_rename_monthly_limit_budget_budget_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
