# Generated by Django 4.1.7 on 2023-04-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickbudget', '0004_rename_budget_id_expense_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='budget',
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='quickbudget.budget'),
        ),
    ]
