# Generated by Django 4.1.7 on 2023-04-11 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickbudget', '0005_remove_expense_budget_expense_budget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
